version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codveda_ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 5000
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: codveda_ecommerce
      JWT_SECRET: change_this_to_a_long_random_string
      JWT_EXPIRES_IN: 7d
      CLIENT_ORIGIN: http://localhost:5173
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend-react
      args:
        VITE_API_URL: http://localhost:5000/api
        VITE_SOCKET_URL: http://localhost:5000
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
